service_name: travis-ci
json_path: ./coveralls-upload.json
coverage_clover:
- docker-output/wpunit/_output/coverage.xml
- docker-output/functional/_output/coverage.xml
- docker-output/acceptance/_output/coverage.xml
