# Codecov configuration
# https://docs.codecov.com/docs/codecov-yaml

codecov:
  notify:
    require_ci_to_pass: yes

# Fix path prefixes from Docker container paths to repo-relative paths
# Note: The workflow already handles path mapping via sed before upload,
# so this section is optional. If needed, add specific plugin mappings here:
# fixes:
#   - "/var/www/html/wp-content/plugins/plugin-name/::plugins/plugin-name/"

# Ignore test files and tools from coverage calculations
ignore:
  - '**/tests'
  - '**/test'
  - '**/*.test.*'
  - '**/*Test.php'
  - 'tools/**'
  - 'bin/**'

coverage:
  precision: 1
  round: nearest
  status:
    project:
      default:
        # Require coverage to maintain or increase compared to base branch
        # Allows up to 1% drop to account for flaky tests
        target: auto
        threshold: 1%
    patch:
      default:
        # Require new code coverage to maintain or increase (auto target)
        # This is more lenient than 100% but still enforces improvement
        target: auto

comment:
  # Show coverage diff in PR comments
  layout: "reach,diff,flags,files"
  behavior: default
  require_changes: false
  require_base: no
  require_head: yes

# Group coverage by test type and configuration
# Using wildcard patterns to automatically include all plugins
# Includes: src/ directory, root-level PHP files, and deprecated/ directory
flags:
  wpunit:
    paths:
      - plugins/*/src/
      - plugins/*/*.php
      - plugins/*/deprecated/
    carryforward: true
  # Theme flags
  twentytwentyfive:
    paths:
      - plugins/*/src/
      - plugins/*/*.php
      - plugins/*/deprecated/
    carryforward: true
  twentytwentyone:
    paths:
      - plugins/*/src/
      - plugins/*/*.php
      - plugins/*/deprecated/
    carryforward: true
  # Multisite flags
  single:
    paths:
      - plugins/*/src/
      - plugins/*/*.php
      - plugins/*/deprecated/
    carryforward: true
  multisite:
    paths:
      - plugins/*/src/
      - plugins/*/*.php
      - plugins/*/deprecated/
    carryforward: true
