# Codecov configuration
# https://docs.codecov.com/docs/codecov-yaml
#
# NOTE: If coverage reports aren't showing on PRs after switching from master to main,
# CodeCov's dashboard doesn't have a UI option to change the default branch.
# You need to contact CodeCov support to have them update your repository's default
# branch from "master" to "main" on their backend.
# 
# Reference: https://github.com/codecov/codecov-action/issues/242

codecov:
  notify:
    require_ci_to_pass: yes

# Fix path prefixes from Docker container paths to repo-relative paths
# Note: The workflow already handles path mapping via sed before upload,
# so this section is optional. If needed, add specific plugin mappings here:
# fixes:
#   - "/var/www/html/wp-content/plugins/plugin-name/::plugins/plugin-name/"

# Ignore test files and tools from coverage calculations
ignore:
  - '**/tests'
  - '**/test'
  - '**/*.test.*'
  - '**/*Test.php'
  - 'tools/**'
  - 'bin/**'

coverage:
  precision: 1
  round: nearest
  status:
    project:
      default:
        # Require coverage to maintain or increase compared to base branch
        # Allows up to 1% drop to account for flaky tests
        target: auto
        threshold: 1%
    patch:
      default:
        # Require new code coverage to maintain or increase (auto target)
        # This is more lenient than 100% but still enforces improvement
        target: auto

comment:
  # Show coverage diff in PR comments
  layout: "reach,diff,flags,files"
  behavior: default
  require_changes: false
  require_base: no
  require_head: yes

# Group coverage by test type and configuration
# Flags are now combined as: plugin-wpunit-theme-multisite (e.g., wp-graphql-wpunit-twentytwentyfive-single)
# Using wildcard patterns to match all flag combinations
# Includes: src/ directory, root-level PHP files, and deprecated/ directory
flags:
  # Match all combined flags (plugin-wpunit-theme-multisite)
  "*-wpunit-*-*":
    paths:
      - plugins/*/src/
      - plugins/*/*.php
      - plugins/*/deprecated/
    carryforward: true
