<?php

namespace Tests\WPGraphQL\Acf\Functional;

use FunctionalTester;

abstract class AcfProFieldCest extends AcfFieldCest {

	public function _before( FunctionalTester $I ): void {
		$I->loginAsAdmin();
		$I->amOnPluginsPage();
		$active_plugins = $I->grabOptionFromDatabase( 'active_plugins' );
		codecept_debug( $active_plugins );

		// ACF PRO fields should only be tested when ACF PRO is active
		if ( ! in_array( 'advanced-custom-fields-pro/acf.php', $active_plugins, true  ) ) {
			$I->markTestSkipped( 'ACF Pro is not active. ACF Pro fields will not be available when the PRO version is not active' );
		}
		parent::_before( $I ); // TODO: Change the autogenerated stub
	}

}
