<?php
/**
 * Asset enqueue + bootstrap data for the React IDE.
 *
 * @package WPGraphQLIDE
 */

declare(strict_types = 1);

namespace WPGraphQLIDE;

/**
 * Enqueues the IDE's JS / CSS bundles and serializes the bootstrap
 * data (`window.WPGRAPHQL_IDE_DATA`) the React app reads on mount.
 */
class AssetEnqueue {

	/**
	 * Enqueues the React application script and associated styles.
	 *
	 * @param bool $bypass_dedicated_page_gate When true, skip the
	 *                                          capability + admin-bar gates
	 *                                          that normally restrict this
	 *                                          to logged-in IDE users on
	 *                                          the right pages. The
	 *                                          public-endpoint render passes
	 *                                          true here because it serves
	 *                                          anonymous visitors by design.
	 */
	public static function enqueue( bool $bypass_dedicated_page_gate = false ): void {
		if ( is_legacy_ide_page() ) {
			return;
		}

		if ( ! class_exists( '\WPGraphQL\Router' ) ) {
			return;
		}

		if ( ! $bypass_dedicated_page_gate ) {
			if ( ! user_has_graphql_ide_capability() ) {
				return;
			}

			// On frontend, only enqueue if admin bar is showing.
			if ( ! is_admin() ) {
				if ( ! is_admin_bar_showing() ) {
					return;
				}
			}
		}

		// Don't enqueue new styles/scripts on the legacy IDE page.
		if ( function_exists( 'get_current_screen' ) ) {
			$screen = get_current_screen();

			if ( $screen instanceof \WP_Screen && 'toplevel_page_graphiql-ide' === $screen->id ) {
				return;
			}
		}

		// Check if build assets exist before including them.
		// Build assets are generated by `npm run build` and may not exist in development.
		$asset_file_path         = WPGRAPHQL_IDE_PLUGIN_DIR_PATH . 'build/wpgraphql-ide.asset.php';
		$render_asset_file_path  = WPGRAPHQL_IDE_PLUGIN_DIR_PATH . 'build/wpgraphql-ide-render.asset.php';
		$graphql_asset_file_path = WPGRAPHQL_IDE_PLUGIN_DIR_PATH . 'build/graphql.asset.php';

		// Bail early if required build assets don't exist.
		if ( ! file_exists( $asset_file_path ) || ! file_exists( $render_asset_file_path ) || ! file_exists( $graphql_asset_file_path ) ) {
			return;
		}

		// phpcs:ignore WordPressVIPMinimum.Files.IncludingFile.UsingVariable -- Path is validated with file_exists() above
		$asset_file = include $asset_file_path;
		// phpcs:ignore WordPressVIPMinimum.Files.IncludingFile.UsingVariable -- Path is validated with file_exists() above
		$render_asset_file = include $render_asset_file_path;
		// phpcs:ignore WordPressVIPMinimum.Files.IncludingFile.UsingVariable -- Path is validated with file_exists() above
		$graphql_asset_file = include $graphql_asset_file_path;

		$app_context = self::app_context();

		wp_register_script(
			'graphql',
			plugins_url( 'build/graphql.js', WPGRAPHQL_IDE_PLUGIN_FILE ),
			$graphql_asset_file['dependencies'],
			$graphql_asset_file['version'],
			true // Load in footer.
		);

		wp_enqueue_script(
			'wpgraphql-ide',
			plugins_url( 'build/wpgraphql-ide.js', WPGRAPHQL_IDE_PLUGIN_FILE ),
			array_merge( $asset_file['dependencies'], [ 'graphql' ] ),
			$asset_file['version'],
			true
		);

		$user_id                 = get_current_user_id();
		$collapsed_notices       = get_user_meta( $user_id, 'wpgraphql_ide_collapsed_notices', true );
		$personal_collections    = get_user_meta( $user_id, 'wpgraphql_ide_personal_collections', true );
		$seen_shared_collections = get_user_meta( $user_id, 'wpgraphql_ide_seen_shared_collections', true );
		$shared_collections      = UserMeta::aggregate_shared_collections();

		// Decode the JSON-string blob into an array for the bootstrap so
		// the client doesn't have to parse on every read. An invalid /
		// missing value falls back to an empty object so the JS hydrator
		// always sees a stable shape.
		$section_states_raw = get_user_meta( $user_id, 'wpgraphql_ide_section_states', true );
		$section_states     = is_string( $section_states_raw ) && '' !== $section_states_raw
			? json_decode( $section_states_raw, true )
			: [];
		if ( ! is_array( $section_states ) ) {
			$section_states = [];
		}

		$localized_data = [
			'nonce'                 => wp_create_nonce( 'wp_rest' ),
			'restUrl'               => esc_url_raw( rest_url() ),
			'graphqlEndpoint'       => trailingslashit( site_url() ) . 'index.php?' . \WPGraphQL\Router::$route,
			'rootElementId'         => WPGRAPHQL_IDE_ROOT_ELEMENT_ID,
			'context'               => $app_context,
			'isDedicatedIdePage'    => current_screen_is_dedicated_ide_page(),
			'dedicatedIdeBaseUrl'   => self::dedicated_ide_base_url(),
			'collapsedNotices'      => is_array( $collapsed_notices ) ? $collapsed_notices : [],
			'personalCollections'   => is_array( $personal_collections ) ? $personal_collections : [],
			'sharedCollections'     => $shared_collections,
			'seenSharedCollections' => is_array( $seen_shared_collections ) ? $seen_shared_collections : [],
			'sectionStates'         => empty( $section_states ) ? new \stdClass() : $section_states,
			// `manage_graphql_ide` is the gate for using the IDE at all, but
			// the share dialog needs to search and resolve other users — that
			// requires `list_users`, which is a strict subset of editor and
			// administrator. Surface it as a separate flag so the client can
			// hide the share affordance for IDE users who can't enumerate
			// other users (e.g. authors granted IDE access via a custom cap).
			'capabilities'          => [
				'listUsers' => current_user_can( 'list_users' ),
			],
		];

		/**
		 * Allow internal modules and external extensions to inject keys into the
		 * IDE's bootstrap data (window.WPGRAPHQL_IDE_DATA).
		 *
		 * @param array<string,mixed> $localized_data The bootstrap data being passed to the IDE.
		 * @param array<string,mixed> $app_context    The current app context.
		 */
		$localized_data = apply_filters( 'wpgraphql_ide_localized_data', $localized_data, $app_context );

		$escaped_data = self::localize_escaped_data( $localized_data );

		wp_localize_script(
			'wpgraphql-ide',
			'WPGRAPHQL_IDE_DATA',
			$escaped_data
		);

		// Extensions looking to extend GraphiQL can hook in here, after the
		// window object is established but before the App renders.
		do_action( 'wpgraphql_ide_enqueue_script', $app_context );

		wp_enqueue_script(
			'wpgraphql-ide-render',
			plugins_url( 'build/wpgraphql-ide-render.js', WPGRAPHQL_IDE_PLUGIN_FILE ),
			array_merge( $asset_file['dependencies'], [ 'wpgraphql-ide', 'graphql' ] ),
			$render_asset_file['version'],
			true
		);

		wp_enqueue_style( 'wp-components' );
		wp_enqueue_style( 'wpgraphql-ide-render', plugins_url( 'build/wpgraphql-ide-render.css', WPGRAPHQL_IDE_PLUGIN_FILE ), [], $render_asset_file['version'] );

		// Avoid running custom styles through a build process for an improved developer experience.
		wp_enqueue_style( 'wpgraphql-ide', plugins_url( 'styles/wpgraphql-ide.css', WPGRAPHQL_IDE_PLUGIN_FILE ), [], $asset_file['version'] );
	}

	/**
	 * Modifies the script tag for specific scripts to add the 'defer' attribute.
	 *
	 * @param string $tag    The HTML <script> tag of the enqueued script.
	 * @param string $handle The script's registered handle in WordPress.
	 * @return string Modified script tag with 'defer' attribute included if handle matches; otherwise, unchanged.
	 */
	public static function defer_script_attribute( string $tag, string $handle ): string {
		if ( 'wpgraphql-ide' === $handle ) {
			return str_replace( ' src', ' defer="defer" src', $tag );
		}

		return $tag;
	}

	/**
	 * Retrieves the base URL for the dedicated WPGraphQL IDE page.
	 *
	 * @return string The URL for the dedicated IDE page within the WordPress admin.
	 */
	public static function dedicated_ide_base_url(): string {
		return menu_page_url( 'graphql-ide', false );
	}

	/**
	 * Retrieves the specific header of this plugin.
	 *
	 * @param string $key The plugin data key.
	 * @return string|null The header value, or null if not found.
	 */
	public static function plugin_header( string $key = '' ): ?string {
		if ( ! function_exists( 'get_plugin_data' ) ) {
			require_once ABSPATH . 'wp-admin/includes/plugin.php';
		}

		if ( empty( $key ) ) {
			return null;
		}

		$plugin_data = get_plugin_data( WPGRAPHQL_IDE_PLUGIN_FILE );

		if ( ! is_array( $plugin_data ) ) {
			return null;
		}

		$plugin_header = $plugin_data[ $key ] ?? null;

		return is_string( $plugin_header ) ? $plugin_header : null;
	}

	/**
	 * Retrieves and sanitizes external fragments.
	 *
	 * @return array<string> The sanitized array of external fragments.
	 */
	public static function external_fragments(): array {
		// Retrieve external fragments using the filter.
		$external_fragments = apply_filters( 'wpgraphql_ide_external_fragments', [] );

		// Loop through each fragment, sanitize, and ensure it's a valid GraphQL fragment.
		return array_filter(
			array_map( 'sanitize_text_field', $external_fragments ),
			static function ( string $fragment ): bool {
				// Check if the fragment starts with "fragment" and contains "on" (basic GraphQL fragment validation).
				return preg_match( '/^fragment\s+\w+\s+on\s+\w+\s*{/', trim( $fragment ) ) === 1;
			}
		);
	}

	/**
	 * Recursive function to escape an array or value for safe output, specifically for localizing data in WordPress.
	 *
	 * @param mixed $data The data to escape.
	 * @return mixed The escaped data.
	 */
	public static function localize_escaped_data( $data ) {
		if ( is_array( $data ) ) {
			return array_map( [ self::class, 'localize_escaped_data' ], $data );
		}
		if ( is_string( $data ) ) {
			// Use wp_kses_post to allow basic HTML for content and esc_url for URLs.
			return filter_var( $data, FILTER_VALIDATE_URL ) ? esc_url( $data ) : wp_kses_post( $data );
		}
		if ( is_int( $data ) ) {
			return absint( $data );
		}
		if ( is_bool( $data ) ) {
			return (bool) $data;
		}

		return $data; // Return original value if it's not a string, int, or bool.
	}

	/**
	 * Retrieves app context.
	 *
	 * @return array<string, mixed> The possibly filtered app context array.
	 */
	public static function app_context(): array {
		$current_user = wp_get_current_user();

		// Get the avatar URL for the current user. Returns an empty string if no user is logged in.
		$avatar_url = $current_user->exists() ? ( get_avatar_url( $current_user->ID ) ?: '' ) : '';

		$app_context = [
			'pluginVersion'     => self::plugin_header( 'Version' ),
			'pluginName'        => self::plugin_header( 'Name' ),
			'externalFragments' => self::external_fragments(),
			'avatarUrl'         => $avatar_url,
			'drawerButtonLabel' => __( 'GraphQL IDE', 'wpgraphql-ide' ),
			// 0 for anonymous, post id otherwise. localStorage buckets
			// (unsaved tabs, etc.) scope by this so signed-in and anonymous
			// state on the same browser don't pollute each other.
			'currentUserId'     => (int) $current_user->ID,
		];

		return apply_filters( 'wpgraphql_ide_context', $app_context );
	}
}
