<?php
namespace Tests\WPGraphQL\Acf\WPUnit;

abstract class AcfeFieldTestCase extends \Tests\WPGraphQL\Acf\WPUnit\AcfFieldTestCase {

	public function setUp(): void {

		// if ACF PRO is not active, skip the test as ACF Extended only works with ACF PRO
		if ( ! defined( 'ACF_PRO' ) ) {
			$this->markTestSkipped( 'ACF Pro is not active so this test will not run.' );
		}

		// If ACF Extended is not active, acfe_* field types are not registered; skip (CI runs some matrix rows without ACF Extended).
		$field_types = acf_get_field_types();
		if ( ! array_key_exists( $this->get_field_type(), $field_types ) ) {
			$this->markTestSkipped( 'ACF Extended is not active; ' . $this->get_field_type() . ' is not available.' );
		}

		parent::setUp(); // TODO: Change the autogenerated stub
	}

	public function tearDown(): void {
		parent::tearDown(); // TODO: Change the autogenerated stub
	}

	/**
	 * Return the acf "field_type". ex. "text", "textarea", "flexible_content", etc
	 * @return string
	 */
	abstract public function get_field_type(): string;

	public function testFieldExists(): void {
		$field_types = acf_get_field_types();
		$this->assertTrue( array_key_exists( $this->get_field_type(), $field_types ) );
	}

}
