<?php

class CommentLocationTest extends \Codeception\TestCase\WPTestCase {

	public $group_key;
	public $post_id;
	public $test_image;
	public $tag_id;
	public $comment_id;

	public function setUp(): void {

		parent::setUp(); // TODO: Change the autogenerated stub
		$this->group_key = __CLASS__;
		WPGraphQL::clear_schema();

		$this->register_acf_field_group();

		$this->post_id = $this->factory()->post->create( [
			'post_type'    => 'post',
			'post_status'  => 'publish',
			'post_title'   => 'Test',
			'post_content' => 'test',
		] );

		$this->tag_id = $this->factory()->term->create( [
			'taxonomy' => 'post_tag',
		] );

		$this->comment_id = $this->factory()->comment->create([
			'comment_content' => 'test comment',
			'comment_author' => 'Test Author',
			'comment_approved' => true,
			'comment_post_ID' => $this->post_id,
 		]);

		$this->test_image = dirname( __FILE__, 2 ) . '/_data/images/test.png';

	}

	public function tearDown(): void {
		acf_remove_local_field_group( $this->group_key );
		wp_delete_post( $this->post_id, true );
		WPGraphQL::clear_schema();
		parent::tearDown(); // TODO: Change the autogenerated stub
	}

	public function register_acf_field_group( $config = [] ) {

		$defaults = [
			'key'                   => $this->group_key,
			'title'                 => 'Comment Fields',
			'fields'                => [],
			'location'              => [
				[
					[
						'param'    => 'comment',
						'operator' => '==',
						'value'    => 'all',
					],
				],
			],
			'menu_order'            => 0,
			'position'              => 'normal',
			'style'                 => 'default',
			'label_placement'       => 'top',
			'instruction_placement' => 'label',
			'hide_on_screen'        => '',
			'active'                => true,
			'description'           => '',
			'show_in_graphql'       => 1,
			'graphql_field_name'    => 'commentTestFields',
			'graphql_types'         => [ 'Comment' ]
		];

		acf_add_local_field_group( array_merge( $defaults, $config ) );


	}

	public function register_acf_field( $config = [] ) {

		$defaults = [
			'parent'            => $this->group_key,
			'key'               => 'field_5d7812fd123',
			'label'             => 'Text',
			'name'              => 'text',
			'type'              => 'text',
			'instructions'      => '',
			'required'          => 0,
			'conditional_logic' => 0,
			'wrapper'           => array(
				'width' => '',
				'class' => '',
				'id'    => '',
			),
			'show_in_graphql'   => 1,
			'default_value'     => '',
			'placeholder'       => '',
			'prepend'           => '',
			'append'            => '',
			'maxlength'         => '',
		];

		acf_add_local_field( array_merge( $defaults, $config ) );
	}

	/**
	 * @throws Exception
	 */
	public function testBasicQuery() {
		$query  = '{ comments { nodes { id } } }';
		$actual = graphql( [ 'query' => $query ] );
		$this->assertArrayNotHasKey( 'errors', $actual );
	}

	public function testAcfTextField() {

		// There was a bug in some versions of WPGraphQL where databaseId wasn't exposed on comments
		// this is a polyfill as we're not really interested in testing comments, just the ACF fields on comments
		add_filter( 'graphql_allowed_fields_on_restricted_type', function( $fields, $model_name ) {

			if ( 'CommentObject' === $model_name && ! isset( $fields['databaseId' ] ) ) {
				$fields[] = 'databaseId';
			}

			return $fields;
		}, 10, 2 );

		$this->register_acf_field([
			'name' => 'comment_text_field_test',
			'type' => 'text',
		]);

		$expected_text = 'Some Text';

		update_field( 'comment_text_field_test', $expected_text, 'comment_' . $this->comment_id );
		$field = get_field( 'comment_text_field_test', 'comment_' . $this->comment_id, true );
		codecept_debug( [ 'field_value', $field, 'comment_' . $this->comment_id ] );

		$query = '
		query getComment( $id: ID! ) {
			comment( id: $id ) {
				__typename
				commentTestFields {
					fieldGroupName
					commentTextFieldTest
				}
			}
		}
		';

		$actual = graphql([
			'query' => $query,
			'variables' => [
				'id' => \GraphQLRelay\Relay::toGlobalId( 'comment', $this->comment_id ),
			],
		]);

		codecept_debug( $actual );

		$this->assertArrayNotHasKey( 'errors', $actual );
		$this->assertSame( $expected_text, $actual['data']['comment']['commentTestFields']['commentTextFieldTest'] );

	}

}
