<?php

class TermLocationTest extends \Codeception\TestCase\WPTestCase {

	/**
	 * @var string
	 */
	public $group_key;

	/**
	 * @var int
	 */
	public $post_id;

	/**
	 * @var string
	 */
	public $test_image;

	/**
	 * @var int
	 */
	public $tag_id;

	public function setUp(): void {

		parent::setUp(); // TODO: Change the autogenerated stub
		$this->group_key = __CLASS__;
		WPGraphQL::clear_schema();
		$this->register_acf_field_group();

		$this->post_id = $this->factory()->post->create( [
			'post_type'    => 'post',
			'post_status'  => 'publish',
			'post_title'   => 'Test',
			'post_content' => 'test',
		] );

		$this->tag_id = $this->factory()->term->create( [
			'taxonomy' => 'post_tag',
		] );

		$this->test_image = dirname( __FILE__, 2 ) . '/_data/images/test.png';

	}

	public function tearDown(): void {
		acf_remove_local_field_group( $this->group_key );
		wp_delete_post( $this->post_id, true );
		WPGraphQL::clear_schema();
		parent::tearDown(); // TODO: Change the autogenerated stub
	}

	public function register_acf_field_group( $config = [] ) {

		$defaults = [
			'key'                   => $this->group_key,
			'title'                 => 'Tag Fields',
			'fields'                => [],
			'location'              => [
				[
					[
						'param'    => 'taxonomy',
						'operator' => '==',
						'value'    => 'post_tag',
					],
				],
			],
			'menu_order'            => 0,
			'position'              => 'normal',
			'style'                 => 'default',
			'label_placement'       => 'top',
			'instruction_placement' => 'label',
			'hide_on_screen'        => '',
			'active'                => true,
			'description'           => '',
			'show_in_graphql'       => 1,
			'graphql_field_name'    => 'tagFields',
			'graphql_types'         => [ 'Tag' ]
		];

		acf_add_local_field_group( array_merge( $defaults, $config ) );


	}

	public function register_acf_field( $config = [] ) {

		$defaults = [
			'parent'            => $this->group_key,
			'key'               => 'field_5d7812fd123',
			'label'             => 'Text',
			'name'              => 'text',
			'type'              => 'text',
			'instructions'      => '',
			'required'          => 0,
			'conditional_logic' => 0,
			'wrapper'           => array(
				'width' => '',
				'class' => '',
				'id'    => '',
			),
			'show_in_graphql'   => 1,
			'default_value'     => '',
			'placeholder'       => '',
			'prepend'           => '',
			'append'            => '',
			'maxlength'         => '',
		];

		acf_add_local_field( array_merge( $defaults, $config ) );
	}

	/**
	 * @throws Exception
	 */
	public function testBasicQuery() {
		$query  = '{ tags { nodes { id } } }';
		$actual = graphql( [ 'query' => $query ] );
		$this->assertArrayNotHasKey( 'errors', $actual );
	}

	public function testAcfTextField() {

		$this->register_acf_field([
			'name' => 'tag_text_field',
			'type' => 'text',
		]);

		$expected_text = 'Some Text';

		update_field( 'tag_text_field', $expected_text, 'post_tag_' . $this->tag_id );
		$field = get_field( 'tag_text_field', 'post_tag_' . $this->tag_id, true );
		codecept_debug( [ 'field_value', $field, 'post_tag_' . $this->tag_id ] );

		$query = '
		query getTag( $id: ID! ) {
			tag( id: $id idType: DATABASE_ID ) {
				databaseId
				tagFields {
					fieldGroupName
					tagTextField
				}
			}
		}
		';

		$actual = graphql([
			'query' => $query,
			'variables' => [
				'id' => $this->tag_id,
			],
		]);

		codecept_debug( $actual );

		$this->assertArrayNotHasKey( 'errors', $actual );
		$this->assertSame( $this->tag_id, $actual['data']['tag']['databaseId'] );
		$this->assertSame( $expected_text, $actual['data']['tag']['tagFields']['tagTextField'] );

	}

}
