<?php
class AATest extends \Codeception\TestCase\WPTestCase {

	public function setUp() {
		parent::setUp(); // TODO: Change the autogenerated stub
	}

	public function tearDown() {
		parent::tearDown(); // TODO: Change the autogenerated stub
	}

	public function testPosts() {
		$query = '{
			test
		}';

		$actual = graphql([
			'query' => $query,
		]);

		codecept_debug( $actual );

	}

	public function testTests() {
		$query = '{
			posts {
			  nodes {
			    title
			  }
			}
		}';

		$actual = graphql([
			'query' => $query,
		]);

		codecept_debug( $actual );

	}

	public function testGoos() {

		register_post_type( 'goo', [
			'show_in_graphql' => true,
			'graphql_single_name' => 'goo',
			'graphql_plural_name' => 'goos'
		] );

		$query = '{
			goos {
			  nodes {
			    id
			    title
			  }
			}
		}';

		$actual = graphql([
			'query' => $query,
		]);

		codecept_debug( $actual );

	}

}
